version: '3.8'

services:
  postgres:
    image: 'postgres:13.1-alpine'
    container_name: postgres_db
    environment:
      POSTGRES_DB: employee_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: spring_backend
    ports:
      - '8082:8081'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/employee_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
    container_name: nextjs_frontend
    ports:
      - '3000:3000'
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://localhost:8082/api/employees
    depends_on:
      - backend

volumes:
  postgres_data: